### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by IsaiahPatton** [CodeCrafter47/Rainbow#2]
Plugins: PluginBukkitBridge.jar (Loads fine)

Crash Report File:

---- Minecraft Crash Report ----

Time: 7/30/16 6:19 PM
Description: Watching Server

java.lang.Error
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.projectrainbow.plugins.PluginClassLoader.findClass(PluginClassLoader.java:61)
	at org.projectrainbow.plugins.PluginManager.getClassByName(PluginManager.java:287)
	at org.projectrainbow.plugins.PluginClassLoader.findClass(PluginClassLoader.java:57)
	at org.projectrainbow.plugins.PluginClassLoader.findClass(PluginClassLoader.java:49)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at PluginBukkitBridge.WorldManager.refresh(WorldManager.java:21)
	at PluginBukkitBridge.MyPlugin.onServerFullyLoaded(MyPlugin.java:192)
	at org.projectrainbow.Hooks.onServerFullyLoaded(Hooks.java:394)
	at ld.handler$onServerFullyLoaded$0(SourceFile:67)
	at ld.j(SourceFile:251)
	at net.minecraft.server.MinecraftServer.run(SourceFile:428)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.projectrainbow.plugins.PluginClassLoader.findClass(PluginClassLoader.java:61)
	at org.projectrainbow.plugins.PluginManager.getClassByName(PluginManager.java:287)
	at org.projectrainbow.plugins.PluginClassLoader.findClass(PluginClassLoader.java:57)
	at org.projectrainbow.plugins.PluginClassLoader.findClass(PluginClassLoader.java:49)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at PluginBukkitBridge.WorldManager.refresh(WorldManager.java:21)
	at PluginBukkitBridge.MyPlugin.onServerFullyLoaded(MyPlugin.java:192)
	at org.projectrainbow.Hooks.onServerFullyLoaded(Hooks.java:394)
	at ld.handler$onServerFullyLoaded$0(SourceFile:67)
	at ld.j(SourceFile:251)

-- Thread Dump --
Details:
	Threads: "Server Watchdog" Id=24 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:446)
	at le.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:745)

"Netty Server IO #0" Id=19 RUNNABLE (in native)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@175d246f
	-  locked java.util.Collections$UnmodifiableSet@cd3188
	-  locked sun.nio.ch.WindowsSelectorImpl@262f6ea6
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
	...

"Server console handler" Id=18 RUNNABLE (in native)
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:272)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:273)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	-  locked java.io.BufferedInputStream@740967df
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	-  locked java.io.InputStreamReader@3210b113
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	...

"DestroyJavaVM" Id=17 RUNNABLE

"Server thread" Id=15 RUNNABLE
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	...

"Server Infinisleeper" Id=14 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at ld$1.run(SourceFile:79)

"Snooper Timer" Id=13 WAITING on java.util.TaskQueue@45c13a68
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@45c13a68
	at java.lang.Object.wait(Object.java:503)
	at java.util.TimerThread.mainLoop(Timer.java:526)
	at java.util.TimerThread.run(Timer.java:505)

"Attach Listener" Id=5 RUNNABLE

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@10e1a59f
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@10e1a59f
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@4e407261
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@4e407261
	at java.lang.Object.wait(Object.java:503)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)

Stacktrace:
	at le.run(SourceFile:59)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_79, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 363508128 bytes (346 MB) / 532152320 bytes (507 MB) up to 1814036480 bytes (1730 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'Rainbow'
	Type: Dedicated Server (map_server.txt)

**Comment by CodeCrafter47** [comment]
Steps to reproduce?

**Comment by IsaiahPatton** [comment]
Run the server

[18:31:01] [INFO]: Preparing spawn area: 98%
[18:31:02] [INFO]: Done (74.128s)! For help, type "help" or "?"
[18:31:02] [FATAL]: A single server tick took 82.32 seconds (should be max 0.05)
[18:31:02] [FATAL]: Considering it to be crashed, server will forcibly shutdown.

It looks like to be an error with the bukkit bridge due to:

at PluginBukkitBridge.WorldManager.refresh(WorldManager.java:21)
at PluginBukkitBridge.MyPlugin.onServerFullyLoaded(MyPlugin.java:192)
at org.projectrainbow.Hooks.onServerFullyLoaded(Hooks.java:394)
